version: "3"
services:
  app:
    container_name: nest-todo
    restart: "always"
    build: .
    ports:
      - "9001:9000"
    networks: 
      - backend

networks: 
  backend:
    driver: "bridge"
